### ISSUE TITLE
Rangefinder displaying distance to next base too late

### ISSUE THREAD

**Issue by MadByteDE** [togfoxy/MarsLander#188] opened 2021-11-07 09:03 UTC
Has to do with the changes to the generation code.

We need to determine position for bases early on without generating the base at the same time.

I'll post my idea shortly.

**Comment by MadByteDE** [comment] 2021-11-07 09:22
```lua
-- PSEUDO-CODE (untested)
local random = love.math.random
local bases = {}
local baseObjects = {}
local updateDistance = 2000
local baseWidth, baseHeight = garrImages[2]:getDimensions()

-- Can be any lander in future
local lander = garrLanders[1]

-- Generate the base positions
function Terrain.generateBasePositions(amount)
	local lastBaseX = basePositions[#basePositions]
	for i = 1, amount do
		-- TODO: The random range values shouldn't be hardcoded
		local base = {}
		base.x = lastBaseX * random(1.25, 2)
		-- Set y outside of visible range for now
		-- Will be set when the terrain is generated
		base.y = -baseHeight
		table.insert(bases, base)
	end
end

-- Spawn/despawn the actual object
function Terrain.updateBases()
	for _, base in ipairs(bases) do
		-- Remove base objects behind the lander
		if base.x <= lander.x - updateDistance then
			-- Bases in the objects table use the x position as key
			table.remove(baseObjects, base.x)

		-- Spawn new base objects ahead of the lander
		elseif base.x < lander.x + updateDistance then
			cobjs.CreateObject(2, base.x)
		end
	end
end
```

Something like this.

**Comment by togfoxy** [comment] 2021-11-07 13:20
I need to sleep. Will check in the morning. 

Thanks!

**Comment by togfoxy** [comment] 2021-11-07 22:29
Unfortunately this won't fix the rangerfinder problem.

The crusx of the issue is that we are determining/drawing 2000 'metres' ahead (or whatever) but as you progress the distance between bases can easily be > 2000, meaning, the rangefinder doesn't "activate" until the lander is within drawing distance.

We need to extend the drawing distance (which is causing the current poor performance) or determine all bases up front and separate out the drawing routines.

**Comment by togfoxy** [comment] 2021-11-07 22:52
I think we just need to cap the drawing distance and the range finder to some value like 5000 'metres'. When flying at max speed anything about 3000 is quite meaningless.

**Comment by MadByteDE** [comment] 2021-11-08 04:13
> Unfortunately this won't fix the rangerfinder problem.
> 

It would fix it, we just need to use the x that gets pregenerated in the bases table instead of the x for the actual object. :thumbsup:

Another option would be to have deterministic x positions that can be calculated on the fly. Then we wouldn't need to store anything previously, but I dont know how to do that just yet.

**Comment by togfoxy** [comment] 2021-11-08 05:42
There is a PR that fixes this. Hopefully.

**Comment by togfoxy** [comment] 2021-11-09 03:39
This issue is not related to Milestone v0.11 (performance issues) but it is a bug fix so will leave in this milestone because bug fixes should have a high priority.

**Comment by togfoxy** [comment] 2021-11-09 14:35
I have a building draw  and range finder bug fix on a branch in my repo. 

I'll create a PR when the two existing PR's are merged.

**Comment by togfoxy** [comment] 2021-11-10 14:03
This is fixed in tonight's PR merge.

**Closed by togfoxy** 2021-11-10 14:03 UTC
Labels: bug
